/**
 * AUTO-GENERATED MSW handlers from OpenAPI schema.
 *
 * DO NOT EDIT THIS FILE MANUALLY!
 * Run `npm run generate:mocks` to regenerate from /api/openapi.json
 *
 * For custom handlers, use handlers.manual.ts instead.
 *
 * Generated at: 2024-12-21
 */

import { http, HttpResponse } from 'msw'

// ============================================================================
// Auth API Handlers
// ============================================================================

const authHandlers = [
  // POST /api/v1/auth/login
  http.post('/api/v1/auth/login', async ({ request }) => {
    const formData = await request.formData()
    const username = formData.get('username')
    const password = formData.get('password')

    // Simulate validation
    if (!username || !password) {
      return HttpResponse.json(
        { detail: 'Missing credentials' },
        { status: 422 }
      )
    }

    // Simulate invalid credentials
    if (password === 'wrongpassword') {
      return HttpResponse.json(
        { detail: 'Invalid credentials' },
        { status: 401 }
      )
    }

    return HttpResponse.json({
      access_token: 'mock-access-token-' + Date.now(),
      refresh_token: 'mock-refresh-token-' + Date.now(),
      token_type: 'bearer',
    })
  }),

  // POST /api/v1/auth/refresh
  http.post('/api/v1/auth/refresh', async ({ request }) => {
    const body = await request.json() as { refresh_token?: string }

    if (!body.refresh_token || body.refresh_token === 'invalid') {
      return HttpResponse.json(
        { detail: 'Invalid refresh token' },
        { status: 401 }
      )
    }

    return HttpResponse.json({
      access_token: 'mock-new-access-token-' + Date.now(),
      refresh_token: 'mock-new-refresh-token-' + Date.now(),
      token_type: 'bearer',
    })
  }),

  // GET /api/v1/auth/me
  http.get('/api/v1/auth/me', ({ request }) => {
    const authHeader = request.headers.get('Authorization')

    if (!authHeader || !authHeader.startsWith('Bearer ')) {
      return HttpResponse.json(
        { detail: 'Not authenticated' },
        { status: 401 }
      )
    }

    return HttpResponse.json({
      id: 'user-123',
      email: 'test@example.com',
      full_name: 'Test User',
      is_active: true,
      is_superuser: false,
      role: {
        id: 'role-1',
        name: 'user',
      },
    })
  }),
]

// ============================================================================
// Documents API Handlers
// ============================================================================

const documentsHandlers = [
  // GET /api/v1/documents/types
  http.get('/api/v1/documents/types', ({ request }) => {
    const authHeader = request.headers.get('Authorization')
    if (!authHeader) {
      return HttpResponse.json({ detail: 'Not authenticated' }, { status: 401 })
    }

    return HttpResponse.json([
      {
        id: 'type-1',
        name: 'audio',
        display_name: 'Audio',
        description: 'Audio files',
        registered_by: 'upload',
        mime_types: ['audio/mpeg', 'audio/wav'],
      },
      {
        id: 'type-2',
        name: 'transcription',
        display_name: 'Transcription',
        description: 'Transcribed text',
        registered_by: 'audio_transcription',
        mime_types: ['application/json'],
      },
    ])
  }),

  // GET /api/v1/documents
  http.get('/api/v1/documents', ({ request }) => {
    const authHeader = request.headers.get('Authorization')
    if (!authHeader) {
      return HttpResponse.json({ detail: 'Not authenticated' }, { status: 401 })
    }

    const url = new URL(request.url)
    const page = parseInt(url.searchParams.get('page') || '1')
    const pageSize = parseInt(url.searchParams.get('page_size') || '10')

    return HttpResponse.json({
      documents: [
        {
          id: 'doc-1',
          type_id: 'type-1',
          type: { id: 'type-1', name: 'audio', display_name: 'Audio' },
          owner_id: 'user-123',
          storage_plugin: 'upload',
          filepath: '/files/audio.mp3',
          content_type: 'audio/mpeg',
          size_bytes: 1024000,
          properties: { original_filename: 'audio.mp3' },
          created_at: '2024-01-01T00:00:00Z',
          updated_at: '2024-01-01T00:00:00Z',
        },
      ],
      total: 1,
      page,
      page_size: pageSize,
    })
  }),

  // GET /api/v1/documents/:id
  http.get('/api/v1/documents/:id', ({ request, params }) => {
    const authHeader = request.headers.get('Authorization')
    if (!authHeader) {
      return HttpResponse.json({ detail: 'Not authenticated' }, { status: 401 })
    }

    const { id } = params

    if (id === 'not-found') {
      return HttpResponse.json({ detail: 'Document not found' }, { status: 404 })
    }

    return HttpResponse.json({
      id,
      type_id: 'type-1',
      type: { id: 'type-1', name: 'audio', display_name: 'Audio' },
      owner_id: 'user-123',
      storage_plugin: 'upload',
      filepath: '/files/audio.mp3',
      content_type: 'audio/mpeg',
      size_bytes: 1024000,
      properties: { original_filename: 'audio.mp3' },
      created_at: '2024-01-01T00:00:00Z',
      updated_at: '2024-01-01T00:00:00Z',
    })
  }),

  // GET /api/v1/documents/:id/children
  http.get('/api/v1/documents/:id/children', ({ request, params }) => {
    const authHeader = request.headers.get('Authorization')
    if (!authHeader) {
      return HttpResponse.json({ detail: 'Not authenticated' }, { status: 401 })
    }

    const { id } = params

    if (id === 'not-found') {
      return HttpResponse.json({ detail: 'Document not found' }, { status: 404 })
    }

    return HttpResponse.json([
      {
        id: 'child-1',
        type_id: 'type-2',
        type: { id: 'type-2', name: 'transcription', display_name: 'Transcription' },
        parent_id: id,
        owner_id: 'user-123',
        storage_plugin: 'upload',
        filepath: '/files/transcription.json',
        content_type: 'application/json',
        size_bytes: 2048,
        properties: {},
        created_at: '2024-01-01T01:00:00Z',
        updated_at: '2024-01-01T01:00:00Z',
      },
    ])
  }),

  // DELETE /api/v1/documents/:id
  http.delete('/api/v1/documents/:id', ({ request, params }) => {
    const authHeader = request.headers.get('Authorization')
    if (!authHeader) {
      return HttpResponse.json({ detail: 'Not authenticated' }, { status: 401 })
    }

    const { id } = params

    if (id === 'not-found') {
      return HttpResponse.json({ detail: 'Document not found' }, { status: 404 })
    }

    return new HttpResponse(null, { status: 204 })
  }),
]

// ============================================================================
// Sources API Handlers
// ============================================================================

const sourcesHandlers = [
  // GET /api/v1/sources
  http.get('/api/v1/sources', ({ request }) => {
    const authHeader = request.headers.get('Authorization')
    if (!authHeader) {
      return HttpResponse.json({ detail: 'Not authenticated' }, { status: 401 })
    }

    return HttpResponse.json([
      {
        id: 'source-1',
        name: 'My Device',
        description: 'Mobile phone',
        api_key_prefix: 'ua_abc',
        is_active: true,
        properties: {},
        owner_id: 'user-123',
        created_at: '2024-01-01T00:00:00Z',
      },
    ])
  }),

  // POST /api/v1/sources
  http.post('/api/v1/sources', async ({ request }) => {
    const authHeader = request.headers.get('Authorization')
    if (!authHeader) {
      return HttpResponse.json({ detail: 'Not authenticated' }, { status: 401 })
    }

    const body = await request.json() as { name?: string; description?: string }

    if (!body.name) {
      return HttpResponse.json(
        { detail: [{ loc: ['body', 'name'], msg: 'field required' }] },
        { status: 422 }
      )
    }

    return HttpResponse.json({
      id: 'source-new',
      name: body.name,
      description: body.description || null,
      api_key: 'ua_mock_api_key_' + Date.now(),
      api_key_prefix: 'ua_moc',
      is_active: true,
      properties: {},
      owner_id: 'user-123',
      created_at: new Date().toISOString(),
    }, { status: 201 })
  }),

  // GET /api/v1/sources/:id
  http.get('/api/v1/sources/:id', ({ request, params }) => {
    const authHeader = request.headers.get('Authorization')
    if (!authHeader) {
      return HttpResponse.json({ detail: 'Not authenticated' }, { status: 401 })
    }

    const { id } = params

    if (id === 'not-found') {
      return HttpResponse.json({ detail: 'Source not found' }, { status: 404 })
    }

    return HttpResponse.json({
      id,
      name: 'My Device',
      description: 'Mobile phone',
      api_key_prefix: 'ua_abc',
      is_active: true,
      properties: {},
      owner_id: 'user-123',
      created_at: '2024-01-01T00:00:00Z',
    })
  }),

  // PATCH /api/v1/sources/:id
  http.patch('/api/v1/sources/:id', async ({ request, params }) => {
    const authHeader = request.headers.get('Authorization')
    if (!authHeader) {
      return HttpResponse.json({ detail: 'Not authenticated' }, { status: 401 })
    }

    const { id } = params

    if (id === 'not-found') {
      return HttpResponse.json({ detail: 'Source not found' }, { status: 404 })
    }

    const body = await request.json() as { name?: string; description?: string }

    return HttpResponse.json({
      id,
      name: body.name || 'My Device',
      description: body.description || 'Mobile phone',
      api_key_prefix: 'ua_abc',
      is_active: true,
      properties: {},
      owner_id: 'user-123',
      created_at: '2024-01-01T00:00:00Z',
    })
  }),

  // DELETE /api/v1/sources/:id
  http.delete('/api/v1/sources/:id', ({ request, params }) => {
    const authHeader = request.headers.get('Authorization')
    if (!authHeader) {
      return HttpResponse.json({ detail: 'Not authenticated' }, { status: 401 })
    }

    const { id } = params

    if (id === 'not-found') {
      return HttpResponse.json({ detail: 'Source not found' }, { status: 404 })
    }

    return new HttpResponse(null, { status: 204 })
  }),

  // POST /api/v1/sources/:id/regenerate-key
  http.post('/api/v1/sources/:id/regenerate-key', ({ request, params }) => {
    const authHeader = request.headers.get('Authorization')
    if (!authHeader) {
      return HttpResponse.json({ detail: 'Not authenticated' }, { status: 401 })
    }

    const { id } = params

    if (id === 'not-found') {
      return HttpResponse.json({ detail: 'Source not found' }, { status: 404 })
    }

    return HttpResponse.json({
      id,
      name: 'My Device',
      description: 'Mobile phone',
      api_key: 'ua_new_api_key_' + Date.now(),
      api_key_prefix: 'ua_new',
      is_active: true,
      properties: {},
      owner_id: 'user-123',
      created_at: '2024-01-01T00:00:00Z',
    })
  }),
]

// ============================================================================
// Plugins API Handlers
// ============================================================================

const pluginsHandlers = [
  // GET /api/v1/plugins
  http.get('/api/v1/plugins', ({ request }) => {
    const authHeader = request.headers.get('Authorization')
    if (!authHeader) {
      return HttpResponse.json({ detail: 'Not authenticated' }, { status: 401 })
    }

    return HttpResponse.json([
      {
        name: 'upload',
        display_name: 'Upload',
        version: '1.0.0',
        description: 'File upload plugin',
        is_enabled: true,
        priority: 10,
        max_concurrent_jobs: 5,
        input_types: [],
        output_type: null,
        dependencies: [],
        color: '#3B82F6',
        state: 'active',
      },
      {
        name: 'audio_transcription',
        display_name: 'Audio Transcription',
        version: '1.0.0',
        description: 'Transcribe audio files',
        is_enabled: true,
        priority: 20,
        max_concurrent_jobs: 2,
        input_types: ['audio'],
        output_type: 'transcription',
        dependencies: ['upload'],
        color: '#10B981',
        state: 'active',
      },
    ])
  }),

  // GET /api/v1/plugins/:name
  http.get('/api/v1/plugins/:name', ({ request, params }) => {
    const authHeader = request.headers.get('Authorization')
    if (!authHeader) {
      return HttpResponse.json({ detail: 'Not authenticated' }, { status: 401 })
    }

    const { name } = params

    if (name === 'not-found') {
      return HttpResponse.json({ detail: 'Plugin not found' }, { status: 404 })
    }

    return HttpResponse.json({
      name,
      display_name: name === 'upload' ? 'Upload' : 'Audio Transcription',
      version: '1.0.0',
      description: name === 'upload' ? 'File upload plugin' : 'Transcribe audio',
      is_enabled: true,
      priority: name === 'upload' ? 10 : 20,
      max_concurrent_jobs: name === 'upload' ? 5 : 2,
      input_types: name === 'upload' ? [] : ['audio'],
      output_type: name === 'upload' ? null : 'transcription',
      dependencies: name === 'upload' ? [] : ['upload'],
      color: name === 'upload' ? '#3B82F6' : '#10B981',
      state: 'active',
    })
  }),

  // POST /api/v1/plugins/:name/enable
  http.post('/api/v1/plugins/:name/enable', ({ request, params }) => {
    const authHeader = request.headers.get('Authorization')
    if (!authHeader) {
      return HttpResponse.json({ detail: 'Not authenticated' }, { status: 401 })
    }

    // Check for superuser (simplified check)
    const { name } = params

    return HttpResponse.json({
      name,
      is_enabled: true,
      message: `Plugin ${name} enabled`,
    })
  }),

  // POST /api/v1/plugins/:name/disable
  http.post('/api/v1/plugins/:name/disable', ({ request, params }) => {
    const authHeader = request.headers.get('Authorization')
    if (!authHeader) {
      return HttpResponse.json({ detail: 'Not authenticated' }, { status: 401 })
    }

    const { name } = params

    return HttpResponse.json({
      name,
      is_enabled: false,
      message: `Plugin ${name} disabled`,
    })
  }),

  // PUT /api/v1/plugins/:name/settings
  http.put('/api/v1/plugins/:name/settings', async ({ request, params }) => {
    const authHeader = request.headers.get('Authorization')
    if (!authHeader) {
      return HttpResponse.json({ detail: 'Not authenticated' }, { status: 401 })
    }

    const { name } = params
    const body = await request.json()

    return HttpResponse.json({
      name,
      settings: body,
      message: `Settings updated for ${name}`,
    })
  }),

  // GET /api/v1/plugins/:name/filters
  http.get('/api/v1/plugins/:name/filters', ({ request }) => {
    const authHeader = request.headers.get('Authorization')
    if (!authHeader) {
      return HttpResponse.json({ detail: 'Not authenticated' }, { status: 401 })
    }

    return HttpResponse.json([
      {
        id: 'filter-1',
        plugin_name: 'audio_transcription',
        filter_type: 'source',
        operator: 'equals',
        value: 'source-1',
        created_at: '2024-01-01T00:00:00Z',
      },
    ])
  }),

  // POST /api/v1/plugins/:name/filters
  http.post('/api/v1/plugins/:name/filters', async ({ request, params }) => {
    const authHeader = request.headers.get('Authorization')
    if (!authHeader) {
      return HttpResponse.json({ detail: 'Not authenticated' }, { status: 401 })
    }

    const { name } = params
    const body = await request.json() as { filter_type?: string; operator?: string; value?: string }

    return HttpResponse.json({
      id: 'filter-new',
      plugin_name: name,
      filter_type: body.filter_type,
      operator: body.operator,
      value: body.value,
      created_at: new Date().toISOString(),
    }, { status: 201 })
  }),

  // DELETE /api/v1/plugins/:name/filters/:filterId
  http.delete('/api/v1/plugins/:name/filters/:filterId', ({ request, params }) => {
    const authHeader = request.headers.get('Authorization')
    if (!authHeader) {
      return HttpResponse.json({ detail: 'Not authenticated' }, { status: 401 })
    }

    const { filterId } = params

    if (filterId === 'not-found') {
      return HttpResponse.json({ detail: 'Filter not found' }, { status: 404 })
    }

    return new HttpResponse(null, { status: 204 })
  }),

  // GET /api/v1/plugins/jobs
  http.get('/api/v1/plugins/jobs', ({ request }) => {
    const authHeader = request.headers.get('Authorization')
    if (!authHeader) {
      return HttpResponse.json({ detail: 'Not authenticated' }, { status: 401 })
    }

    const url = new URL(request.url)
    const status = url.searchParams.get('status')
    const pluginName = url.searchParams.get('plugin_name')

    const jobs = [
      {
        id: 'job-1',
        document_id: 'doc-1',
        plugin_name: 'audio_transcription',
        status: 'completed',
        progress: 100,
        progress_message: 'Done',
        result: { transcript: 'Hello world' },
        error_message: null,
        output_document_id: 'doc-2',
        started_at: '2024-01-01T00:00:00Z',
        completed_at: '2024-01-01T00:01:00Z',
        created_at: '2024-01-01T00:00:00Z',
      },
      {
        id: 'job-2',
        document_id: 'doc-3',
        plugin_name: 'audio_transcription',
        status: 'running',
        progress: 50,
        progress_message: 'Processing...',
        result: null,
        error_message: null,
        output_document_id: null,
        started_at: '2024-01-01T00:02:00Z',
        completed_at: null,
        created_at: '2024-01-01T00:02:00Z',
      },
    ]

    // Filter by status and plugin_name if provided
    let filtered = jobs
    if (status) {
      filtered = filtered.filter(j => j.status === status)
    }
    if (pluginName) {
      filtered = filtered.filter(j => j.plugin_name === pluginName)
    }

    return HttpResponse.json(filtered)
  }),

  // GET /api/v1/plugins/jobs/:id
  http.get('/api/v1/plugins/jobs/:id', ({ request, params }) => {
    const authHeader = request.headers.get('Authorization')
    if (!authHeader) {
      return HttpResponse.json({ detail: 'Not authenticated' }, { status: 401 })
    }

    const { id } = params

    if (id === 'not-found') {
      return HttpResponse.json({ detail: 'Job not found' }, { status: 404 })
    }

    return HttpResponse.json({
      id,
      document_id: 'doc-1',
      plugin_name: 'audio_transcription',
      status: 'completed',
      progress: 100,
      progress_message: 'Done',
      result: { transcript: 'Hello world' },
      error_message: null,
      output_document_id: 'doc-2',
      started_at: '2024-01-01T00:00:00Z',
      completed_at: '2024-01-01T00:01:00Z',
      created_at: '2024-01-01T00:00:00Z',
    })
  }),

  // POST /api/v1/plugins/jobs/:id/cancel
  http.post('/api/v1/plugins/jobs/:id/cancel', ({ request, params }) => {
    const authHeader = request.headers.get('Authorization')
    if (!authHeader) {
      return HttpResponse.json({ detail: 'Not authenticated' }, { status: 401 })
    }

    const { id } = params

    if (id === 'not-found') {
      return HttpResponse.json({ detail: 'Job not found' }, { status: 404 })
    }

    if (id === 'completed') {
      return HttpResponse.json(
        { detail: 'Cannot cancel completed job' },
        { status: 400 }
      )
    }

    return HttpResponse.json({
      id,
      status: 'cancelled',
      message: 'Job cancelled',
    })
  }),
]

// ============================================================================
// Upload Plugin Handlers
// ============================================================================

const uploadHandlers = [
  // POST /api/v1/plugins/upload/files
  http.post('/api/v1/plugins/upload/files', async ({ request }) => {
    const authHeader = request.headers.get('Authorization')
    const apiKey = request.headers.get('X-API-Key')

    if (!authHeader && !apiKey) {
      return HttpResponse.json({ detail: 'Not authenticated' }, { status: 401 })
    }

    // Simulate file upload
    return HttpResponse.json({
      id: 'doc-new-' + Date.now(),
      type_id: 'type-1',
      type: { id: 'type-1', name: 'audio', display_name: 'Audio' },
      owner_id: 'user-123',
      storage_plugin: 'upload',
      filepath: '/files/uploaded-' + Date.now() + '.mp3',
      content_type: 'audio/mpeg',
      size_bytes: 1024000,
      properties: { original_filename: 'test.mp3' },
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    }, { status: 201 })
  }),
]

// ============================================================================
// Export all handlers
// ============================================================================

export const handlers = [
  ...authHandlers,
  ...documentsHandlers,
  ...sourcesHandlers,
  ...pluginsHandlers,
  ...uploadHandlers,
]
