"""add_user_workflow_steps

Revision ID: 0269b1b38152
Revises: 1a01046d8c32
Create Date: 2025-12-26 14:27:51.898438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0269b1b38152'
down_revision: Union[str, None] = '1a01046d8c32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_workflow_steps',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('plugin_name', sa.String(length=100), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_workflow_type', 'user_workflow_steps', ['user_id', 'document_type'], unique=False)
    op.create_index('idx_user_workflow_unique', 'user_workflow_steps', ['user_id', 'document_type', 'sequence_number'], unique=True)
    op.create_index('idx_user_workflow_user', 'user_workflow_steps', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_workflow_user', table_name='user_workflow_steps')
    op.drop_index('idx_user_workflow_unique', table_name='user_workflow_steps')
    op.drop_index('idx_user_workflow_type', table_name='user_workflow_steps')
    op.drop_table('user_workflow_steps')
    # ### end Alembic commands ###
