"""add_source_workflow_steps

Revision ID: 1a01046d8c32
Revises: 5a2e5faec3f2
Create Date: 2025-12-24 15:46:42.501378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a01046d8c32'
down_revision: Union[str, None] = '5a2e5faec3f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_workflow_steps',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('plugin_name', sa.String(length=100), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_source_workflow_source', 'source_workflow_steps', ['source_id'], unique=False)
    op.create_index('idx_source_workflow_type', 'source_workflow_steps', ['source_id', 'document_type'], unique=False)
    op.create_index('idx_source_workflow_unique', 'source_workflow_steps', ['source_id', 'document_type', 'sequence_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_source_workflow_unique', table_name='source_workflow_steps')
    op.drop_index('idx_source_workflow_type', table_name='source_workflow_steps')
    op.drop_index('idx_source_workflow_source', table_name='source_workflow_steps')
    op.drop_table('source_workflow_steps')
    # ### end Alembic commands ###
